M48
; DRILL file {KiCad (6.0.1-0)} date Friday, October 07, 2022 at 11:17:43 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-07T23:17:43-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.925Y-2.925
X4.925Y-4.825
X6.35Y-2.925
X6.35Y-4.825
T0
M30
