M48
; DRILL file {KiCad (6.0.1-0)} date Monday, October 24, 2022 at 06:59:55 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-24T18:59:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.925Y-2.925
X4.925Y-4.925
X6.425Y-2.925
X6.425Y-4.925
T0
M30
