M48
; DRILL file {KiCad (6.0.1-0)} date Thursday, December 01, 2022 at 11:09:13 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-01T23:09:13-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.925Y-2.925
X4.925Y-4.925
X6.425Y-2.925
X6.425Y-4.925
T0
M30
